IGNORE_AUDIO = [
    "XC444635",
    "bcwea1/XC283454.ogg",
    "brcsta1/XC294767.ogg",
    "stusta1/XC344767.ogg",
    "gobwea1/XC642423.ogg",
    "gobwea1/XC756461.ogg",
    "hunsun2/XC294881.ogg",
    "chespa1/XC397507.ogg",
    "rufcha2/XC396571.ogg",
    "marsto1/XC137756.ogg",
    "bawman1/XC320114.ogg",
    "whrshr1/XC239949.ogg",
    "dutdov1/XC237297.ogg",
    "chewea1/XC234618.ogg",
    "chewea1/XC172184.ogg",
    "bubwar2/XC195533.ogg",
    "bubwar2/XC281985.ogg",
    "gytbar1/XC137782.ogg",
    "whcpri2/XC319165.ogg",
    "whcpri2/XC666260.ogg",
    "kvbsun1/XC459159.ogg",
    "refwar2/XC172869.ogg",
    "refwar2/XC525931.ogg",
    "XC248014.ogg",
    "XC722271.ogg"
]

label_dict = {0: 'abethr1',
              1: 'abhori1',
              2: 'abythr1',
              3: 'afbfly1',
              4: 'afdfly1',
              5: 'afecuc1',
              6: 'affeag1',
              7: 'afgfly1',
              8: 'afghor1',
              9: 'afmdov1',
              10: 'afpfly1',
              11: 'afpkin1',
              12: 'afpwag1',
              13: 'afrgos1',
              14: 'afrgrp1',
              15: 'afrjac1',
              16: 'afrthr1',
              17: 'amesun2',
              18: 'augbuz1',
              19: 'bagwea1',
              20: 'barswa',
              21: 'bawhor2',
              22: 'bawman1',
              23: 'bcbeat1',
              24: 'beasun2',
              25: 'bkctch1',
              26: 'bkfruw1',
              27: 'blacra1',
              28: 'blacuc1',
              29: 'blakit1',
              30: 'blaplo1',
              31: 'blbpuf2',
              32: 'blcapa2',
              33: 'blfbus1',
              34: 'blhgon1',
              35: 'blhher1',
              36: 'blksaw1',
              37: 'blnmou1',
              38: 'blnwea1',
              39: 'bltapa1',
              40: 'bltbar1',
              41: 'bltori1',
              42: 'blwlap1',
              43: 'brcale1',
              44: 'brcsta1',
              45: 'brctch1',
              46: 'brcwea1',
              47: 'brican1',
              48: 'brobab1',
              49: 'broman1',
              50: 'brosun1',
              51: 'brrwhe3',
              52: 'brtcha1',
              53: 'brubru1',
              54: 'brwwar1',
              55: 'bswdov1',
              56: 'btweye2',
              57: 'bubwar2',
              58: 'butapa1',
              59: 'cabgre1',
              60: 'carcha1',
              61: 'carwoo1',
              62: 'categr',
              63: 'ccbeat1',
              64: 'chespa1',
              65: 'chewea1',
              66: 'chibat1',
              67: 'chtapa3',
              68: 'chucis1',
              69: 'cibwar1',
              70: 'cohmar1',
              71: 'colsun2',
              72: 'combul2',
              73: 'combuz1',
              74: 'comsan',
              75: 'crefra2',
              76: 'crheag1',
              77: 'crohor1',
              78: 'darbar1',
              79: 'darter3',
              80: 'didcuc1',
              81: 'dotbar1',
              82: 'dutdov1',
              83: 'easmog1',
              84: 'eaywag1',
              85: 'edcsun3',
              86: 'egygoo',
              87: 'equaka1',
              88: 'eswdov1',
              89: 'eubeat1',
              90: 'fatrav1',
              91: 'fatwid1',
              92: 'fislov1',
              93: 'fotdro5',
              94: 'gabgos2',
              95: 'gargan',
              96: 'gbesta1',
              97: 'gnbcam2',
              98: 'gnhsun1',
              99: 'gobbun1',
              100: 'gobsta5',
              101: 'gobwea1',
              102: 'golher1',
              103: 'grbcam1',
              104: 'grccra1',
              105: 'grecor',
              106: 'greegr',
              107: 'grewoo2',
              108: 'grwpyt1',
              109: 'gryapa1',
              110: 'grywrw1',
              111: 'gybfis1',
              112: 'gycwar3',
              113: 'gyhbus1',
              114: 'gyhkin1',
              115: 'gyhneg1',
              116: 'gyhspa1',
              117: 'gytbar1',
              118: 'hadibi1',
              119: 'hamerk1',
              120: 'hartur1',
              121: 'helgui',
              122: 'hipbab1',
              123: 'hoopoe',
              124: 'huncis1',
              125: 'hunsun2',
              126: 'joygre1',
              127: 'kerspa2',
              128: 'klacuc1',
              129: 'kvbsun1',
              130: 'laudov1',
              131: 'lawgol',
              132: 'lesmaw1',
              133: 'lessts1',
              134: 'libeat1',
              135: 'litegr',
              136: 'litswi1',
              137: 'litwea1',
              138: 'loceag1',
              139: 'lotcor1',
              140: 'lotlap1',
              141: 'luebus1',
              142: 'mabeat1',
              143: 'macshr1',
              144: 'malkin1',
              145: 'marsto1',
              146: 'marsun2',
              147: 'mcptit1',
              148: 'meypar1',
              149: 'moccha1',
              150: 'mouwag1',
              151: 'ndcsun2',
              152: 'nobfly1',
              153: 'norbro1',
              154: 'norcro1',
              155: 'norfis1',
              156: 'norpuf1',
              157: 'nubwoo1',
              158: 'pabspa1',
              159: 'palfly2',
              160: 'palpri1',
              161: 'piecro1',
              162: 'piekin1',
              163: 'pitwhy',
              164: 'purgre2',
              165: 'pygbat1',
              166: 'quailf1',
              167: 'ratcis1',
              168: 'raybar1',
              169: 'rbsrob1',
              170: 'rebfir2',
              171: 'rebhor1',
              172: 'reboxp1',
              173: 'reccor',
              174: 'reccuc1',
              175: 'reedov1',
              176: 'refbar2',
              177: 'refcro1',
              178: 'reftin1',
              179: 'refwar2',
              180: 'rehblu1',
              181: 'rehwea1',
              182: 'reisee2',
              183: 'rerswa1',
              184: 'rewsta1',
              185: 'rindov',
              186: 'rocmar2',
              187: 'rostur1',
              188: 'ruegls1',
              189: 'rufcha2',
              190: 'sacibi2',
              191: 'sccsun2',
              192: 'scrcha1',
              193: 'scthon1',
              194: 'shesta1',
              195: 'sichor1',
              196: 'sincis1',
              197: 'slbgre1',
              198: 'slcbou1',
              199: 'sltnig1',
              200: 'sobfly1',
              201: 'somgre1',
              202: 'somtit4',
              203: 'soucit1',
              204: 'soufis1',
              205: 'spemou2',
              206: 'spepig1',
              207: 'spewea1',
              208: 'spfbar1',
              209: 'spfwea1',
              210: 'spmthr1',
              211: 'spwlap1',
              212: 'squher1',
              213: 'strher',
              214: 'strsee1',
              215: 'stusta1',
              216: 'subbus1',
              217: 'supsta1',
              218: 'tacsun1',
              219: 'tafpri1',
              220: 'tamdov1',
              221: 'thrnig1',
              222: 'trobou1',
              223: 'varsun2',
              224: 'vibsta2',
              225: 'vilwea1',
              226: 'vimwea1',
              227: 'walsta1',
              228: 'wbgbir1',
              229: 'wbrcha2',
              230: 'wbswea1',
              231: 'wfbeat1',
              232: 'whbcan1',
              233: 'whbcou1',
              234: 'whbcro2',
              235: 'whbtit5',
              236: 'whbwea1',
              237: 'whbwhe3',
              238: 'whcpri2',
              239: 'whctur2',
              240: 'wheslf1',
              241: 'whhsaw1',
              242: 'whihel1',
              243: 'whrshr1',
              244: 'witswa1',
              245: 'wlwwar',
              246: 'wookin1',
              247: 'woosan',
              248: 'wtbeat1',
              249: 'yebapa1',
              250: 'yebbar1',
              251: 'yebduc1',
              252: 'yebere1',
              253: 'yebgre1',
              254: 'yebsto1',
              255: 'yeccan1',
              256: 'yefcan',
              257: 'yelbis1',
              258: 'yenspu1',
              259: 'yertin1',
              260: 'yesbar1',
              261: 'yespet1',
              262: 'yetgre1',
              263: 'yewgre1'}

# counts = data.primary_label.value_counts()
# values = counts[counts < 100].index.tolist()
sample_melee_100 = ['tamdov1',
                    'trobou1',
                    'piecro1',
                    'grbcam1',
                    'spmthr1',
                    'vilwea1',
                    'subbus1',
                    'afecuc1',
                    'bcbeat1',
                    'afpwag1',
                    'gobbun1',
                    'sccsun2',
                    'brubru1',
                    'wbswea1',
                    'didcuc1',
                    'litswi1',
                    'yefcan',
                    'chibat1',
                    'blacuc1',
                    'lawgol',
                    'reedov1',
                    'afghor1',
                    'whbcou1',
                    'sincis1',
                    'btweye2',
                    'gyhbus1',
                    'brctch1',
                    'wookin1',
                    'eswdov1',
                    'helgui',
                    'spwlap1',
                    'afrgos1',
                    'reftin1',
                    'blacra1',
                    'gyhkin1',
                    'reccor',
                    'pitwhy',
                    'slcbou1',
                    'blaplo1',
                    'klacuc1',
                    'affeag1',
                    'gycwar3',
                    'crefra2',
                    'squher1',
                    'wfbeat1',
                    'crohor1',
                    'rebfir2',
                    'sichor1',
                    'afrthr1',
                    'quailf1',
                    'gbesta1',
                    'bawhor2',
                    'soufis1',
                    'spemou2',
                    'brwwar1',
                    'lessts1',
                    'refcro1',
                    'gyhspa1',
                    'amesun2',
                    'carwoo1',
                    'blfbus1',
                    'supsta1',
                    'marsun2',
                    'moccha1',
                    'crheag1',
                    'broman1',
                    'yebere1',
                    'spepig1',
                    'walsta1',
                    'whbwhe3',
                    'afmdov1',
                    'strsee1',
                    'sltnig1',
                    'cabgre1',
                    'ruegls1',
                    'yebbar1',
                    'kerspa2',
                    'spewea1',
                    'meypar1',
                    'gabgos2',
                    'beasun2',
                    'scrcha1',
                    'afrjac1',
                    'afdfly1',
                    'darbar1',
                    'hamerk1',
                    'chucis1',
                    'brosun1',
                    'butapa1',
                    'brican1',
                    'rewsta1',
                    'libeat1',
                    'yesbar1',
                    'mouwag1',
                    'wbgbir1',
                    'bkfruw1',
                    'rebhor1',
                    'grwpyt1',
                    'chtapa3',
                    'yetgre1',
                    'abythr1',
                    'gryapa1',
                    'reisee2',
                    'fatrav1',
                    'bswdov1',
                    'afrgrp1',
                    'wtbeat1',
                    'bagwea1',
                    'bltbar1',
                    'ndcsun2',
                    'blnmou1',
                    'slbgre1',
                    'brobab1',
                    'blhgon1',
                    'gyhneg1',
                    'whbtit5',
                    'nubwoo1',
                    'rocmar2',
                    'scthon1',
                    'reboxp1',
                    'soucit1',
                    'sobfly1',
                    'yebgre1',
                    'blcapa2',
                    'somtit4',
                    'grywrw1',
                    'edcsun3',
                    'whbwea1',
                    'bltori1',
                    'afgfly1',
                    'gnhsun1',
                    'norcro1',
                    'norpuf1',
                    'norfis1',
                    'kvbsun1',
                    'luebus1',
                    'yelbis1',
                    'mcptit1',
                    'whrshr1',
                    'litwea1',
                    'norbro1',
                    'raybar1',
                    'hartur1',
                    'vimwea1',
                    'bubwar2',
                    'whcpri2',
                    'huncis1',
                    'mabeat1',
                    'blhher1',
                    'vibsta2',
                    'yebduc1',
                    'refwar2',
                    'tacsun1',
                    'brrwhe3',
                    'yespet1',
                    'fislov1',
                    'easmog1',
                    'blwlap1',
                    'wheslf1',
                    'blnwea1',
                    'witswa1',
                    'pygbat1',
                    'loceag1',
                    'palfly2',
                    'malkin1',
                    'afbfly1',
                    'whihel1',
                    'abethr1',
                    'nobfly1',
                    'rufcha2',
                    'blksaw1',
                    'spfbar1',
                    'ccbeat1',
                    'yeccan1',
                    'joygre1',
                    'lesmaw1',
                    'yenspu1',
                    'augbuz1',
                    'lotlap1',
                    'spfwea1',
                    'refbar2',
                    'macshr1',
                    'marsto1',
                    'dutdov1',
                    'grccra1',
                    'gobwea1',
                    'equaka1',
                    'gytbar1',
                    'sacibi2',
                    'darter3',
                    'chewea1',
                    'chespa1',
                    'brcale1',
                    'bltapa1',
                    'bawman1',
                    'hipbab1',
                    'purgre2',
                    'rostur1',
                    'whbcan1',
                    'whbcro2',
                    'gybfis1',
                    'hunsun2',
                    'rehwea1',
                    'palpri1',
                    'pabspa1',
                    'afpkin1',
                    'dotbar1',
                    'shesta1',
                    'brtcha1',
                    'brcsta1',
                    'brcwea1',
                    'stusta1',
                    'fatwid1',
                    'gobsta5',
                    'rehblu1',
                    'yebsto1',
                    'lotcor1',
                    'golher1',
                    'whctur2',
                    'whhsaw1']