FDJFDFJ = 'ASDASDASDASDASDADASDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDASDASD'

print(FDJFDFJ)


a = 123

def GFWEFF(rt):

    return ('Hello')